/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AteedWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AuditNotificationEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ContentfulAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ContentfulSpaceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GooglePsiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleSheetWebhookUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ImageGenSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}